services:
  goodjob_worker:
    build:
      context: ./Kontravers.GoodJob
      dockerfile: Dockerfile-GoodJobWorker
    depends_on:
      - postgres
  
  postgres:
    image: postgres:15.3
    container_name: goodjob-postgres
    ports:
      - "5432:5432"
    environment:
      PGDATA: '/var/lib/postgresql/data/pgdata'
      POSTGRES_PASSWORD: 'Password1!'
    volumes:
      - psql:/var/lib/postgresql/data
      
networks:
    default:
        external:
            name: kontravers-goodjob
volumes:
  psql:
