services:
  worker:
    build:
      context: ./Kontravers.GoodJob
      dockerfile: Dockerfile-GoodJobWorker
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - kontravers-goodjob

  auth:
    build:
      context: ./Kontravers.GoodJob
      dockerfile: Dockerfile-GoodJobAuth
    ports:
      - "7068:7068" #https
      - "5279:5279" #http
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - kontravers-goodjob
  
  api:
    build:
      context: ./Kontravers.GoodJob
      dockerfile: Dockerfile-GoodJobAPI
    depends_on:
      - postgres
      - worker
      - rabbitmq
    ports:
      - "8010:8010"
    networks:
      - kontravers-goodjob
  
  postgres:
    image: postgres:15.6
    container_name: goodjob-postgres
    ports:
      - "5432:5432"
    environment:
      PGDATA: '/var/lib/postgresql/data/pgdata'
      POSTGRES_PASSWORD: 'Password1!'
    volumes:
      - psql:/var/lib/postgresql/data
    networks:
      - kontravers-goodjob
  
  rabbitmq:
    build:
      context: ./Kontravers.GoodJob
      dockerfile: Dockerfile-RabbitMq
    container_name: goodjob-rabbitmq
    ports:
      - "8080:15672"
      - "5672:5672"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 300M
    networks:
      - kontravers-goodjob
      
networks:
    kontravers-goodjob:
      external: true
      
volumes:
  psql:
