# Build stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /source/goodjob_auth
COPY . .
RUN dotnet restore ./Kontravers.GoodJob.Auth/Kontravers.GoodJob.Auth.csproj
RUN dotnet publish ./Kontravers.GoodJob.Auth/Kontravers.GoodJob.Auth.csproj -c release -o /app/goodjob_auth --no-restore

# Run stage
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app/goodjob_auth
COPY --from=build /app/goodjob_auth ./
ENV ASPNETCORE_URLS=http://+:5279

ENTRYPOINT ["dotnet", "Kontravers.GoodJob.Auth.dll"]