FROM rabbitmq:3.13.0-management

COPY rabbitmq.conf /etc/rabbitmq/
COPY rabbitmq.config /etc/rabbitmq/
COPY definitions.json /etc/rabbitmq/
RUN chown rabbitmq:rabbitmq /etc/rabbitmq/rabbitmq.conf /etc/rabbitmq/definitions.json